### PR TITLE
ay-p request

### PR DESCRIPTION
**Pull request by denyszayets**

### CODE REVIEW

**Comment by dajohi** [comment]
please rebase against master.

**Comment by denyszayets** [comment]
Hi David,
I never made a rebate against master. Can you help me out? I’m more on a front-end development. Thank you

DENYS ZAYETS I am so much more than a job title!
(904) 613-5591 denyszayets.com [http://denyszayets.com/] & @denyszayets [https://twitter.com/denyszayets]
On Wed, Nov 29, 2017 at 14:30, David Hill <notifications@github.com> wrote:
please rebase against master.

**Comment by dajohi** [comment]
Maybe @peterzen can?  I think he did this before...

**Comment by denyszayets** [comment]
I would appreciate it. I can add him to my repo as admin

On Wed, Nov 29, 2017 at 14:46, David Hill <notifications@github.com> wrote:
Maybe @peterzen [https://github.com/peterzen] can? I think he did this before...

**Comment by peterzen** [comment]
@denyszayets Can you please break up this PR into smaller commits?  I can see you've added a logo and updated the mkdocs config, but there are also changes in the README where sections are removed, this is quite likely to be incorrect but there are too many changes for this merge to be safe.

**Comment by denyszayets** [comment]
ok let me try

On Thu, Nov 30, 2017 at 10:55, Peter Banik <notifications@github.com> wrote:
@denyszayets [https://github.com/denyszayets] Can you please break up this PR into smaller commits? I can see you've added a logo and updated the mkdocs config, but there are also changes in the README where sections are removed, this is quite likely to be incorrect but there are too many changes for this merge to be safe.

**Comment by denyszayets** [comment]
Peter,
I totally understand. I’m rebuilding this once again, one step at a time. Will submit changes in small batches ok?

On Thu, Nov 30, 2017 at 12:21, Peter Banik <notifications@github.com> wrote:
@peterzen commented on this pull request.

I can't work out what this PR is about. No commit messages and a huge amount of changes that don't make sense to me. Seems like it has something to do with localization as several MD files were moved but I really can't see the intent of these commits.

**Comment by denyszayets** [comment]
Starting to submit small batch of files required my material theme.

On Thu, Nov 30, 2017 at 12:22, Denys Zayets <denyszayets@gmail.com> wrote:
Peter,
I totally understand. I’m rebuilding this once again, one step at a time. Will submit changes in small batches ok?

On Thu, Nov 30, 2017 at 12:21, Peter Banik <notifications@github.com> wrote:
@peterzen commented on this pull request.

I can't work out what this PR is about. No commit messages and a huge amount of changes that don't make sense to me. Seems like it has something to do with localization as several MD files were moved but I really can't see the intent of these commits.

**Comment by peterzen** [comment]
Excellent!  Smaller chunks of changes are much easier to understand and merge.  Please pay attention to writing meaningful commit messages also, that helps understand the intent of changes – now that you mentioned you're working on a new theme it makes a whole lot more sense to me already :)

**Comment by denyszayets** [comment]
You’re right. I will comment on what’s being added or removed. Will make it as easy as possible. Feedback is always welcome.

On Thu, Nov 30, 2017 at 12:26, Peter Banik <notifications@github.com> wrote:
Excellent! Smaller chunks of changes are much easier to understand and merge. Please pay attention to writing meaningful commit messages also, that helps understand the intent of changes – now that you mentioned you're working on a new theme it makes a whole lot more sense to me already :)

**Comment by denyszayets** [comment]
Peter,
After hours of losing my mind I found the solution. Apparently some of the dependencies used in the old theme were out dated and market in a different way in new versions.
In order for me to confirm that everything works the it’s supposed to work I could upload later 50% of my work in chunks because it would not work on your end 100% positive. So even though initially I sent small chunks of data for your review, in this last part I’m sending bigger size.
At this point major changes were made to mkdocs.yml and package.json
Following folder tpldcrdocs containing old theme files is no longer required and in some cases had some issues of compatibility.
Everything works on my end without any issues. I’m using this site to test docs portal: https://dcrdocs.netlify.com/ [https://dcrdocs.netlify.com/]
Talk to you soon! Denys
On Thu, Nov 30, 2017 at 12:27, Denys Zayets <denyszayets@gmail.com> wrote:
You’re right. I will comment on what’s being added or removed. Will make it as easy as possible. Feedback is always welcome.

On Thu, Nov 30, 2017 at 12:26, Peter Banik <notifications@github.com> wrote:
Excellent! Smaller chunks of changes are much easier to understand and merge. Please pay attention to writing meaningful commit messages also, that helps understand the intent of changes – now that you mentioned you're working on a new theme it makes a whole lot more sense to me already :)

**Pull request closed without merging**
