### PR TITLE
Using Decrediton screenshots

### PR DESCRIPTION
**Pull request by obxium**
- Update all screenshots for **Using Decrediton** to reflect version 1.1.3 and address #443
- Remove trailing spaces

### CODE REVIEW

**Comment by alexlyp** [comment]
Looks great!  Though can you do this now for the recently updated v1.2.0 (just released yesterday)?

**Comment by obxium** [comment]
Sure! I had an issue getting 1.2.0 working yesterday, but I'll try again and update this.

**Comment by obxium** [comment]
Got 1.2.0 and am getting updated screenshots now

**Comment by obxium** [comment]
Okay, I updated all screenshots and included some additional ones for future docs updates. I also updated some of the text copy as well. Let me know how else I can help out!

**Comment by dajohi** [comment]
@obxium please rebase on top of current master.  thx.

**Comment by obxium** [comment]
Hi @dajohi I think that I have done that correctly now. Thanks!

**Pull request merged**
