### PR TITLE
#604 decred_supply.png updated

### LINKED ISSUE #604: Update to the coin supply growth chart
The current chart under inflation at https://docs.decred.org/advanced/inflation/ only displays the total DCR supply over time. I suggest updating the chart with an estimate of the coin supply growth with a breakdown of the various ways the block reward is split.  

 
image

### PR DESCRIPTION
**Pull request by zubairzia0**
#604  Made a new chart that displays the estimated growth of the supply with a breakdown for PoW, PoS and dev subsidy in addition to the Total Dcr supply.

Closes #604

### CODE REVIEW

**Comment by jholdstock** [comment]
Also can you please update your PR comment to include a message like "Closes #604". This will make sure the issue is automatically closed when the PR is merged. More info about this can be found here: https://help.github.com/articles/closing-issues-using-keywords/

**Comment by zubairzia0** [comment]
1) I will take the percentage labels away.
2) I will update the PR with the "Closes #604" comment.
2) Horizontal line for Premine would look confusing IMO, since the chart shows supply estimation. 
3) If PoW started at 0 on the inflation page table it could make sense, however, since it starts on 1.68 million the chart and table will be inconsistent.

**Comment by jholdstock** [comment]
Good observation about the table, I think this needs updating.

Was the block reward for block 1 actually 1,680,000? @jrick or @davecgh could you please comment?

I feel like the table should either have a new "Premine" column like this:

Block height | Premine | Block reward (DCR) | PoW (DCR) | PoS vote (DCR) | Dev subsidy (DCR) | Total DCR supply
-- | -- |-- | -- | -- | -- | --
1 | 1,680,000.00 | 0 | 0 | 0 | 0 | 1,680,000
2 | 0 |  21.84 | 18.72 | 0.00 | 3.12 | 1,680,022
4,096 | 0 |  31.20 | 18.72 | 1.87 | 3.12 | 1,769,432

however this column would simply be filled with zeros apart from the first row, so perhaps updating the block reward for block 1 to be zero might be better:

Block height | Block reward (DCR) | PoW (DCR) | PoS vote (DCR) | Dev subsidy (DCR) | Total DCR supply
-- |-- | -- | -- | -- | --
1 |  0 | 0 | 0 | 0 | 1,680,000
2 |  21.84 | 18.72 | 0.00 | 3.12 | 1,680,022
4,096 |   31.20 | 18.72 | 1.87 | 3.12 | 1,769,432

**Comment by jholdstock** [comment]
This chart from https://dcr-data.netlify.com/ shows the "horizontal line" I was describing for the premine. 

chart

I don't think there is anything confusing about this, I think it explains the breakdown of the current supply quite clearly accurately.

**Comment by zubairzia0** [comment]
ok I added the horizontal line and styled the graph a bit. 
image

**Comment by jholdstock** [comment]
I believe the first graph you posted is incorrect - this graph should not have a line for total supply, as all of the other lines (pow, pos, subsidy, airdrop, premine) should sum up to the Total supply. That would match what we see on https://dcr-data.netlify.com/

The second graph is technically correct - however I personally don't find that graph as intuitive as the dcr-data.netlify.com one.

Some feedback from other contributors would be nice here - @RichardRed0x @dajohi @s-ben @noahpierau  do you guys have any opinions?

**Comment by zubairzia0** [comment]
@jholdstock I see what you are saying made the lines stacked now. Look at the first example and see if it now makes more sense. Let me know your thoughts.

**Comment by jholdstock** [comment]
This is good for now, we can bulk update all the terminology on the site when some agreement is reached about what we should call it.

**Pull request merged**
