### PR TITLE
Material Theme & Extensions Update

### PR DESCRIPTION
**Pull request by denyszayets**
1. Added Material theme
2. Updated dependencies and extensions
3. Updated mkdocks.yml
4. Removed old theme folder
5. Updated package.json

Testing site: https://dcrdocs.netlify.com/

Sorry for poor commenting (still learning)

### CODE REVIEW

**Comment by karamble** [comment]
you want linnuttee to verify the design and layout changes of the theme.

all social links in the footer are missing

js and fonts are still loaded from 3rd party webservers

**Comment by dajohi** [comment]
@denyszayets This PR has 18 commits.  Since you are still learning, I would recommend starting small.

Please create a new PR with a single commit that only adds the Material theme.  Do not hook it up to the build;  just git add with a commit message of 'Add material theme'.

**Comment by jholdstock** [comment]
MathJax.js seems to be removed from the repo which has broken the LaTeX formatting - theres some examples [here](https://dcrdocs.netlify.com/research/elliptic-curve-signature-algorithms/)

**Comment by dajohi** [comment]
closed by #419

**Pull request closed without merging**
