### PR TITLE
Use new theme.

### LINKED ISSUE #418: Use 'material' mkdocs theme
The `material` theme for dcrdocs is a vast improvement over what we currently have. Once we have implemented the change over to the basic theme, we can begin to customise with the Decred logo, fonts and color scheme.

### PR DESCRIPTION
**Pull request by jholdstock**
- Update requirements.txt
- Use `material` theme in mk_docs.yml
- Delete old theme in `tpldcrdocs` directory
- Introduce new `theme_override` directory to keep MathJax from the old theme dir

Closes #418

### CODE REVIEW

**Comment by jholdstock** [comment]
Preview of this PR here: http://dcrdocs.jamieholdstock.com/

**Comment by dajohi** [comment]
@jholdstock requires rebase.

**Comment by dajohi** [comment]
Closes #411

**Comment by jholdstock** [comment]
Rebase performed. Test site updated: http://dcrdocs.jamieholdstock.com

**Comment by jholdstock** [comment]
Closes #278.

**Pull request merged**
