### PR TITLE
update to new decred_symbol in dcrdocs icon font

### PR DESCRIPTION
**Pull request by gozart1**
screen shot 2017-02-09 at 1 39 56 am

### CODE REVIEW

**Comment by jcvernaleo** [comment]
Does this PR related to #53 at all?  If that one goes in is this obsolete?  Or do they interfere?

**Comment by gozart1** [comment]
they won't collide, which my why I made a separate PR

**Comment by gozart1** [comment]
I simply updated the font by importing the old svg font into icomoon, replacing the decred icon with the new svg in the design package that was posted in the forum, and exported the font again

**Comment by jcvernaleo** [comment]
@gozart1 Great!  That is kind of what I thought but I wanted confirmation.

**Pull request merged**
