### PR TITLE
Add Poloniex to the list of exchanges

### PR DESCRIPTION
**Pull request by kargakis**

### CODE REVIEW

**Comment by jcvernaleo** [comment]
Thanks!
OK

**Comment by kargakis** [comment]
@jcvernaleo do we also need to update index.html like in https://github.com/decred/dcrdocs/pull/16 ? 

I didn't get to actually build the site and test it

**Comment by jcvernaleo** [comment]
I did a 2nd PR #17 that regenerated the static content.  But yes, generally after changes one needs to use mkdocs -build to regen the site.

**Comment by kargakis** [comment]
@jcvernaleo noted. Thanks

**Pull request merged**
