### PR TITLE
New design based on the master repo

### LINKED ISSUE #52: Custom Theme with new Design
We need to update the theme according to the new Design specifics.

You can find informations on how to customize themes for mkdocs on their user-guide at
http://www.mkdocs.org/user-guide/custom-themes/

Therefore the template have to be created into a single directory which contains all needed assets, HTML, CSS, JS and FONTS. This directory should be created next to the mkdocs.yml configuration file in the document root.

The requirement is to disclaim JS if possible. And if JS have to be used it have to be served locally and the Sites usablility should be ensured, even when NoScript browsing is enabled.

You can activate the new template by editing the mkdocs.yml and point to the directory with the following parameters:
`
theme: null
theme_dir: YOU_THEME_DIRECTORY/
`

### PR DESCRIPTION
**Pull request by karamble**
closes #52 
added directory tpldcrdocs/ with contents of the new design

mkdocs.yml configuration files was edited to make the new design the default

### CODE REVIEW

**Comment by jcvernaleo** [comment]
@karamble how does this related to #53 ?

**Comment by karamble** [comment]
#53 can be removed, because i screwed the #53 PR - it was not mergeable without conflicts so i redit the work

**Comment by jcvernaleo** [comment]
@karamble in the future, do not open new PRs for the same work.  I can help you either help  you fix your branch or replace it with a new one on the same PR.  I've seen some truly amazing messes with git and it is always fixable.

**Comment by jolan** [comment]
#63 can be removed too.  Nothing like 3 PRs for the same thing :-1: :laughing:

**Comment by jolan** [comment]
Looks good to me as well.

**Pull request merged**
