### PR TITLE
 Add dcrdata to explorer section

### LINKED ISSUE #484: When talking about the block explorer, include dcrdata.org
https://docs.decred.org/getting-started/using-the-block-explorer/

### PR DESCRIPTION
**Pull request by noahpierau**
Commits need to be squashed into one

### CODE REVIEW

**Comment by noahpierau** [comment]
This is my first PR to the docs. I'm relatively new to this, so please let me know how to improve next time. I'm working from the GitHub.com editor, so my Git magic is limited

**Comment by raedah** [comment]
Looks okay to me.

**Comment by jholdstock** [comment]
In `agenda-voting.md` we have 
```
The easiest method to track your how your tickets actually voted is to use the [block explorer](https://mainnet.decred.org) to view each of your votes.
```

In `dcrd-setup.md` we have the following sentence:
```
... the last block processed against the last block height on [the official block explorer](https://mainnet.decred.org/). 
```

I would say we should update these to dcrdata links as well

**Comment by noahpierau** [comment]
Hey @jholdstock this PR is called "Add dcrdata to explorer section" in order to fix issue 484, so I focused only on that section. I will open a new issue for the other sections

**Pull request merged**
