### PR TITLE
Paymetheus - Voting address clarification

### PR DESCRIPTION
**Pull request by guyhalestorm**
Clarifies that Ds and Dc addresses are both valid targets for voting addresses.

### CODE REVIEW

**Comment by guyhalestorm** [comment]
And because I was a moron and didn't put the gominer Linux guide in its own branch.... here it apparently is again.  *facepalm*

**Comment by guyhalestorm** [comment]
Yay for newb mistakes.  I'll close this out and remake it.

**Comment by jcvernaleo** [comment]
You don't actually need to close.  Make new branch with same name and force push `git push <REMOTE> <BRANCH> -f`

**Comment by guyhalestorm** [comment]
Screw it, I can't make it work without it pulling in the old commits., I'll just make a new one.

**Pull request closed without merging**
