### PR TITLE
Update logo header

### LINKED ISSUE #606: Header section symbol update
Dcr docs header section needs an updated symbol:
screen shot 2018-09-07 at 15 52 16

Asset:
[decred_logo_symbol_128.svg.zip](https://github.com/decred/dcrdocs/files/2361110/decred_logo_symbol_128.svg.zip)

### PR DESCRIPTION
**Pull request by s-ben**
Updates logo to new color logo (Closes #606). Looks better to me...

Used official symbol from,
https://decred.org/brand/

cropped so it has the same size as previously used symbol (logo.svg).

### CODE REVIEW

**Comment by linnutee** [comment]
Hi, 

Please use only the .svg @saender provided. That's the latest updated version and part of a bigger process for updating the logos and symbols across platforms. 

decred.org/brand is yet to be updated. 

Latest release with identity guidelines is currently here: https://github.com/decred/dcrdesign/releases

**Comment by s-ben** [comment]
Sorry about that. Tried to use the attached logo, but it was blank when I tried to view it in multiple programs. Didn't think it was just white on transparent background (facepalm). Have updated with the correct attached logo. Looks good when I build locally. Will reference the identity guidelines moving forward.

**Comment by jholdstock** [comment]
Hi @s-ben, there seems to be an issue with your PR as it includes unrelated commits: 

> 4b29e90 - updated screenshot for voting preferences  
> a67af06 - ￼Removing replaced screenshot image from repo 

Could you please update this PR or create a new one with only the relevant commit for changing the logo?

Secondly, could you please update your PR comment to include a message like "Closes #606". This will make sure the issue is automatically closed when the PR is merged. More info about this can be found here: https://help.github.com/articles/closing-issues-using-keywords/

**Comment by s-ben** [comment]
Hi @jholdstock. Have rebased and dropped the unrelated commits (I believe), and updated the PR comment so it closes the issue. Hopefully I've figured out the git flow now... I think I may be running into an issue, where even when I create a separate branch for each feature off my forked master branch, commits on the different branches are showing up in commits when I submit a PR to the Decred master branch? Once I'm sure I have my head wrapped around this process, may try and put further guidance in the docs if appropriate.

**Comment by s-ben** [comment]
Redoing PR to clean up git issues.

**Pull request closed without merging**
