### PR TITLE
Remove operating-a-vsp.md

### PR DESCRIPTION
**Pull request by jholdstock**
This will be moved into the vspd repo with other vspd specific doco.

### CODE REVIEW

**Comment by jholdstock** [comment]
#decred/vspd/458

**Review by davecgh — COMMENTED** [review]
What do you think about keeping a link somewhere to the documentation in the vsp repo?  While I agree it's not really reading for a general user, it is generally nice to leave breadcrumbs to help find content imo.

**Comment by jholdstock** [comment]
How about this?

Screenshot from 2023-11-29 07-09-45

**Comment by davecgh** [comment]
That looks good to me.

**Pull request merged**
