### PR TITLE
Updated screenshot for voting preferences (Issue #588)

### LINKED ISSUE #588: Change the screenshot of dropdown list
Replace this image ( https://docs.decred.org/getting-started/user-guides/how-to-vote/ ) 
image
with this one 
dropdown

### PR DESCRIPTION
**Pull request by s-ben**
Screenshot looks good when I render on localhost, 
Closes #588

There is a broken image (voting.jpg) just below this screenshot though, FYI. Can update that screenshot too on this PR if someone posts an image. Can alternately create screenshot myself if someone points me to where to take it.

### CODE REVIEW

**Comment by s-ben** [comment]
@alexlyp , just updating the screen shot [how to vote page](https://docs.decred.org/getting-started/user-guides/how-to-vote/), per this issue,
https://github.com/decred/dcrdocs/issues/588

P.S. was just told the proper way to tag issues in Github and will be doing that moving forward.

**Comment by jholdstock** [comment]
Hi @s-ben,

Thanks for your PR. Could you please delete the old image `stakepool-voting-page.png` which is no longer in use?
Also - you can edit your PR description to include "Closes #588" and it should still close the issue automatically once this is merge (as we discussed on slack).

**Comment by jholdstock** [comment]
I opened a new issue #592 to fix the other broken image

**Comment by s-ben** [comment]
Done. Thx for the info on process. Think I'm good now!

**Pull request merged**
