### PR TITLE
Remove overview pages

### LINKED ISSUE #136: Do we need "Overview" pages?
In particular I am referring to:
- faq/overview.md
- advanced/overview.md

These pages don't seem to contain any unique information and they aren't particularly insightful. Example from the advanced overview: 

> **Block Header Specifications**
> This page describes the Decred block header.

Also because these pages are maintained manually and not automatically generated, they can easily fall out of date. This has already happened and caused PR #135 to be necessary.

mining/overview.md and research/overview.md are different because they do contain information which is not replicated elsewhere, so I guess these should stay.

### PR DESCRIPTION
**Pull request by jholdstock**
Closes #136

### CODE REVIEW

**Comment by jcvernaleo** [comment]
Build fails:
```
jcv@triforce dcrdocs $ ./build_docs.sh 
=======================================
 E N  -  E N G L I S H  V E R S I O N 
INFO	-  Building en_docs into directory site/
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /home/jcv/code/decred/dcrdocs/site 
WARNING -  The page "getting-started/user-guides/web.md" contained a hyperlink to "mining/overview.md" which is not listed in the "pages" configuration. 
WARNING -  The page "getting-started/user-guides/web.md" contained a hyperlink to "mining/overview.md" which is not listed in the "pages" configuration. 
WARNING -  The page "mining/proof-of-stake.md" contained a hyperlink to "mining/overview.md" which is not listed in the "pages" configuration. 
=======================================
de  V E R S I O N 
INFO	-  Comparing Files and copy missing contents from en version
INFO	-  Building de_docs into directory site/de
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /home/jcv/code/decred/dcrdocs/site/de 
WARNING -  The page "getting-started/user-guides/web.md" contained a hyperlink to "mining/overview.md" which is not listed in the "pages" configuration. 
WARNING -  The page "getting-started/user-guides/web.md" contained a hyperlink to "mining/overview.md" which is not listed in the "pages" configuration. 
WARNING -  The page "mining/proof-of-stake.md" contained a hyperlink to "mining/overview.md" which is not listed in the "pages" configuration. 
INFO	-  Remove files and directories site/de/css/ js/ fonts/ Icons/
INFO	-  Symlink site/css/ to site/de/css/ js/ fonts/ Icons/
=======================================
es  V E R S I O N 
INFO	-  Comparing Files and copy missing contents from en version
INFO	-  Building es_docs into directory site/es
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /home/jcv/code/decred/dcrdocs/site/es 
WARNING -  The page "getting-started/user-guides/web.md" contained a hyperlink to "mining/overview.md" which is not listed in the "pages" configuration. 
WARNING -  The page "getting-started/user-guides/web.md" contained a hyperlink to "mining/overview.md" which is not listed in the "pages" configuration. 
WARNING -  The page "mining/proof-of-stake.md" contained a hyperlink to "mining/overview.md" which is not listed in the "pages" configuration. 
INFO	-  Remove files and directories site/es/css/ js/ fonts/ Icons/
INFO	-  Symlink site/css/ to site/es/css/ js/ fonts/ Icons/
jcv@triforce dcrdocs $ 
```

**Comment by jcvernaleo** [comment]
Also, please rebase this before fixing that.

**Comment by jholdstock** [comment]
Done and done.

**Comment by jcvernaleo** [comment]
The build errors are fixed but this was still not rebased correctly against master (and actually does not do it cleanly).

You need to make sure your master is up to date and then do `git rebase -i master <YOURBRANCH>` (don't worry about squashing, I can take care of that)

**Comment by jholdstock** [comment]
OK I think I have done what you are requesting, but I'm not really sure because I can't really see what affect it has had - this PR is just the same 3 commits containing the same set of changes?

**Comment by jcvernaleo** [comment]
That looks right now.  Yes, it is the same set of commits, but you have to see what commit they are starting from.  Normally, github is smart enough to just rebase it for me when I squash them, but in this case it had conflicts so I needed you to do the rebase for me.

**Pull request merged**
