### PR TITLE
Split installation guides into their respective sections.

### LINKED ISSUE #273: Better organization for download and install
Easier to find paymetheus download/install page.

### PR DESCRIPTION
**Pull request by jholdstock**
Closes #273

### CODE REVIEW

**Comment by jholdstock** [comment]
Right - this was only my third time trying a rebase but I'm quite confident I got it right this time. I did make a couple of little mistakes which are fixed in a third commit though.

**Comment by jcvernaleo** [comment]
So other than the one minor fix I requested, I'm happy with this.  Does anyone else have any feedback?  @jolan @karamble @gratefulcheddar?  Figure since it changes the organization a little I should give people a change to speak up if they have concerns.

**Comment by jholdstock** [comment]
Build is no longer failing

**Comment by jcvernaleo** [comment]
So this is all good for me now.  I'm leaving it unmerged for a few hours in case someone else in docs wants to comment.  If I don't hear from someone soon I'll merge it since I'm good with it.

**Comment by jcvernaleo** [comment]
Since there was no objection (and I gave people enough time) this is going in.  Sorry for the delay @jholdstock

**Pull request merged**
