### PR TITLE
New Design Update HTML, JS, CSS, IMG and ICONS

### PR DESCRIPTION
**Pull request by karamble**
#52 This is the initial commit with the HTML,JS, CSS, IMG and ICONS 
contents submitted by Lunitee

This theme serves all those needed assets locally and is using bootstrap, js and webfonts.

Site can be browsed with enabled NoScript with same user experience.
Custom Webfonts and Icons won't be displayed in this case.

You can enable the theme by editing the **mkdocs.yml** file and point to the template directory:
`
theme: null
`
`
theme_dir: tpldcrdocs/
`
The only relevant files for this PR are in the tpldcrdocs/ directoy

### CODE REVIEW

**Comment by gozart1** [comment]
Hey @karamble !

I'm interested in getting involved with Decred and figure I could start here since front end is more my wheelhouse. I ran your PR and wanted to give you some initial feedback.

I'd be happy to make a PR to address these. But figure I'd check with you first since maybe you already took care of these on you local codebase, lmk!

screen shot 2017-02-05 at 1 25 44 pm

screen shot 2017-02-05 at 1 46 22 pm

**Comment by karamble** [comment]
Yeah, you can come to https://github.com/karamble/dcrdocs/tree/newdesign - that is where i am working on, so if you have changes just PR them

**Comment by karamble** [comment]
MathJax Package is 60MB+ so i have not included it and we are serving from 3rd party currently. MathJax is the last 3rd Party package that is used on the side. All Google Fonts are served locally.

**Comment by jcvernaleo** [comment]
@karamble That was pretty much the same thing I came to when I tried remove all third party deps from the docs on master.  I ended up leaving in mathjax due to the size/complexity of it.

**Comment by jcvernaleo** [comment]
Overall, looking great.
Since this is a big change, would it be possible for you to rebase it against master.  I don't think it will happen totally cleanly so github won't be able to do it for me.
I've only tested on Firefox.  Has anyone confirmed that it works on Chrome and maybe something Microsoft (I don't really know what people use there).

**Comment by jcvernaleo** [comment]
One comment on the design itself.  I miss the dark background on the main body of the text.  I liked that much better than the current light background.  Beyond my normal preference, I think the code examples stuck out better in the old design partly due to that.
I assume that the light background is something that isn't going to change despite my opinion (although I'd love to be wrong there) but is there any way we can make the sample commands/code stick out better?

**Comment by gozart1** [comment]
@karamble lmk if you would like a hand w/ squash + rebase this.

@jcvernaleo one idea I had would be to make it a dark bg by default.

But if js is enabled,  insert a "light-bg" class on the body element that would show the current styling. And provide a btn to toggle that class on/off.

Seems like there's a good amount of "no scripters" in the decred community this would be nice hat tip to them. 

But best would probably be to just stick w/ one to keep things simple.

**Comment by jcvernaleo** [comment]
@gozart1 I'm normally in the no-script camp as well, I just happen to whitelist decred.org :)

**Comment by gozart1** [comment]
I can take a crack at doing a squashed + rebased + dark themed version of this PR. 
Could probably have it ready before midnight.

thinking something along the lines of this to keep things consistent
https://twitter.com/decredproject/status/829799048769060867/photo/1

Are there any other sites being overhauled I should be checking out for reference if I go ahead w/ that?

**Comment by jcvernaleo** [comment]
@gozart1 Despite being the one who wants a dark theme, I'd be fine with that being a separate PR.  Probably worth getting this one rebased and then in then get the dark theme.

**Comment by jolan** [comment]
Can you rebase this please?

**Comment by jcvernaleo** [comment]
@karamble is this PR ready to go in once @jolan or I review it?

**Comment by jcvernaleo** [comment]
I will open a separate issue about the light vs dark theme since I think dark looked much better.

**Comment by jcvernaleo** [comment]
Closing in favor of #72

**Pull request closed without merging**
