### PR TITLE
Dark theme, get rid of top bar

### PR DESCRIPTION
**Pull request by gozart1**
https://github.com/decred/dcrdocs/issues/73

Stuff in this PR:
- Dark theme for main content
- Unify navigation/search markup into a single template
- Each page links to github page of current content
- Refactor css a bit ( hence the 877 deletions )

### CODE REVIEW

**Comment by gozart1** [comment]
preview http://dcrdocs.netlify.com/

**Comment by gozart1** [comment]
This is still a WIP, planning to make a few more changes related to:
- refine spacing of content and typography
- toggle between light/dark

**Comment by jcvernaleo** [comment]
What's the status on this one?  Still working on it, or does it need review?

Either way, it does need a rebase when you can.

**Comment by gozart1** [comment]
Made a new PR which includes these changes but keeps the light theme #99

**Pull request closed without merging**
